### ISSUE TITLE
Adding Product to Shelve

### ISSUE THREAD

**Issue by albertoazinar** [LSambo02/dapp#3]
form validation should trigger an error message when adding a product without selecting shelve.

**Comment by LSambo02** [comment]
And also I would suggest we add a pop up or disable the "add product" button if there's no shelve added yet

**Comment by albertoazinar** [comment]
That's a cool feature.

**Comment by albertoazinar** [comment]
Closing this because it's already done on the PR `[#5](https://github.com/LSambo02/dapp/pull/5)`
